<?php 

$querys = [
    "modulesSelectAll" => "SELECT * FROM FU_MODULES",
    "usersSelectAll"   => "SELECT USER_NAMES, CONCAT(LAST_NAME_PAT,LAST_NAME_MAT,NAMES) AS NOMBRE, NR_DOC, PROFILE_ID, WORKSTATION,STATUS_USER FROM FU_USERS"
];      